[tool.black]
line-length = 80

[tool.ruff]
line-length = 80
exclude = ["scripts/__init__.py", "tests/__init__.py"]

[tool.ruff.lint]
select = ["ALL"]
ignore = ["ANN101", "COM812", "G004", "ANN401", "RUF100"]

per-file-ignores = { "tests/*" = ["S101", "D103", "D100", "ANN001", "ARG001"] }

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.format]
quote-style = "preserve"
line-ending = "auto"
docstring-code-format = true
preview = true
