[tool.ruff]
line-length = 80

[tool.ruff.lint]
select = ["ALL"]  # or pick specific rules
ignore = ["COM812"]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.format]
quote-style = "preserve"
line-ending = "auto"
docstring-code-format = true
preview = true  # enables formatting of comments and docstrings
