apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-app
  labels:
    app: home-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: home-app
  template:
    metadata:
      labels:
        app: home-app
    spec:
      serviceAccountName: default
      containers:
        - name: home-app
          image: fogcat5/home-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: uploads
              mountPath: /uploads
            - name: gcp-credentials
              mountPath: /app/service-account-key.json
              subPath: service-account-key.json
          env:
            - name: ALLOWED_USER_EMAILS
              value: "fogcat5@gmail.com"
            - name: ALLOWED_SERVICE_ACCOUNT_IDS
              value: "system:serviceaccount:default:backup-trigger-sa"
          envFrom:
            - secretRef:
                name: tracker-secrets
      volumes:
        - name: uploads
          persistentVolumeClaim:
            claimName: home-app-pvc
        - name: gcp-credentials
          secret:
            secretName: gcp-credentials
