apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: home-app
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-body-size: "16m"
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/use-forwarded-headers: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: home.fogcat5.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: home-app
                port:
                  number: 80
  tls:
    - hosts:
        - home.fogcat5.com
      secretName: home-fogcat5-com-tls
