apiVersion: v1
kind: ServiceAccount
metadata:
  name: backup-trigger-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: allow-backup-trigger
  namespace: default
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]  # Or reduce to least privilege
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bind-backup-trigger
  namespace: default
subjects:
- kind: ServiceAccount
  name: backup-trigger-sa
roleRef:
  kind: Role
  name: allow-backup-trigger
  apiGroup: rbac.authorization.k8s.io
